//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CShip.h
//  @ Date : 2007-04-10
//  @ Author : 
//
//


#if !defined(_CDATA_H)
#define _CDATA_H
#include <string>
using namespace std;

/* 자재 데이터 */
class CMaterial {
public:
	int m_iMaterialID;		/* 자재ID */
	string m_strMaterialType;			/* 자재종류 */
	float m_fStockAmount;				/* 자재재고량 */

	void SetData(int _materialID, string _materialType, float _amount)
	{
		m_iMaterialID = _materialID;
		m_strMaterialType = _materialType;
		m_fStockAmount = _amount;
	}
};

/* 주문서 및 입고지시서 */
class COrder {
public:
	int m_iOrderID;		/* 주문서ID */
	int m_iMaterialID;		/* 자재ID */
	float m_fOrderAmount;			/* 자재주문량 */
	string m_strCompany;			/* 자재주문회사 */
	string m_dateOrderDay;			/* 주문일 */
	string m_dateDueDay;			/* 납기일 */
	bool m_bChecked;				/* 입고여부 */
	string m_dateInputDay;			/* 입력일 */

	void SetData(int _orderID, int _materialID, float _orderAmount, string _company,
		string _orderDay, string _dueDay, bool _checked, string _inputDay = "")
	{
		m_iOrderID = _orderID;
		m_iMaterialID = _materialID;
		m_fOrderAmount = _orderAmount;
		m_strCompany = _company;
		m_dateOrderDay = _orderDay;
		m_dateDueDay = _dueDay;
		m_bChecked = _checked;
		m_dateInputDay = _inputDay;
	}
};

/* 출하 지시서*/
class CShip {
public:
	int m_iShipID;			/* 출하지시서 */
	int m_iMaterialID;		/* 자재ID */
	float m_fShipAmount;			/* 출하량 */
	string m_dateShipDay;			/* 출하예정일 */
	bool m_bChecked;				/* 출하여부 */
	string m_dateInputDay;			/* 입력일 */

public:
	void SetData(int _shipID, int _materialID, float _shipAmount,
		string _dateShipDay, bool _checked, string _inputDay = "")
	{
		m_iShipID = _shipID;
		m_iMaterialID = _materialID;
		m_fShipAmount = _shipAmount;
		m_dateShipDay = _dateShipDay;
		m_bChecked = _checked;
		m_dateInputDay = _inputDay;
	}
};

#endif  //_CDATA_H
