//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CLogin.h
//  @ Date : 2007-04-10
//  @ Author : 
//
//


#if !defined(_CLOGIN_H)
#define _CLOGIN_H

#include <string>
using namespace std;

class CLogin {
public:
	CLogin();
	int checkPW(string _pw);
private:
	string m_iMaterialPW;			/* 자재부 비밀번호 */
	string m_iProducePW;			/* 생산부 비밀번호 */
};

#endif  //_CLOGIN_H
