//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CPMSystem.h
//  @ Date : 2007-04-10
//  @ Author : 
//
//


#if !defined(_CPMSYSTEM_H)
#define _CPMSYSTEM_H

#include "CLogin.h"
#include "CMaterialPart.h"
#include "CProducePart.h"

class CPMSystem {
public:
	CPMSystem();
	~CPMSystem();
	bool Login();
private:
	CLogin* m_login;
	CMaterialPart* m_materialPart;
	CProducePart* m_producePart;

	void CreateMaterialPart();
	void CreateProducePart();
	
	bool ProcessMaterial();
	bool ProcessProduce();
};

#endif  //_CPMSYSTEM_H
