//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CProducePart.h
//  @ Date : 2007-04-10
//  @ Author : 
//
//


#if !defined(_CPRODUCEPART_H)
#define _CPRODUCEPART_H

#include "CData.h"
#include <vector>

using namespace std;

class CProducePart {
public:
	vector<CMaterial> m_materialList;
	vector<CShip> m_shipList;
	bool LoadData();					/* 파일을 로드한다. */
	bool SaveData();					/* 파일을 저장한다. */
	void ShowMaterialAll();				/* 자재정보 전체보기 */
	bool AddShip();						/* 자재출하지시서 입력하기*/
private:
	bool LoadMaterialData();			/* 자재정보 로드 */
	bool LoadShipData();				/* 출하지시서 로드*/
	bool SaveShipData();				/* 출하지시서 저장*/
};

#endif  //_CPRODUCEPART_H
